version: '3.8'

services:
  rpc-tests:
    build:
      context: ../..
      dockerfile: src/rpc-tests/Dockerfile
    volumes:
      - ./reports:/usr/src/app/reports
    env_file:
      - ../../.env
    command: >
      sh -c "if [ \"$TEST_ENV\" = 'local' ]; then npm run test:rpc:local; else npm run test:rpc:testnet; fi"
