config:
  target: "http://127.0.0.1"  # Dummy target
  phases:
    - duration: 60
      arrivalRate: 1
  processor: "./processor.ts"
  engines:
    http: {}

scenarios:
  - name: "fflonk Transactions"
    flow:
      - log: "Starting proof transaction for fflonk"
      - function: "sendProofTransaction_fflonk"
